[nas]
name = "nas1"
ip = "192.168.30.200"
mac = "9c:6b:00:07:bc:85"

[pushgateway]
url = "http://192.168.30.24:9091"

[[targets]]
name = "work_laptop"
ip = "192.168.30.5"
keypath = "/root/.ssh/id_ed25519_worklaptop"
instance = "brun0:worklaptop"
mac = "84:14:4d:f7:2a:c4"
external_path = "/mnt/external/worklaptop_backup"

[[targets]]
name = "gokr_perm"
instance = "brun0:gokr_perm_gmah"
external_path = "/mnt/external/gokrazy_backup"
