[nas]
name = "nas1"
ip = "192.168.30.200"
mac = "9c:6b:00:07:bc:85"

[pushgateway]
url = "http://192.168.30.24:9091"

[external]
name = "external"
external_path = "/mnt/external"
[[external.rsync_commands]]
name = "external_all_except_worklaptop"
command = "-av --delete -e ssh --exclude=template --exclude=snippets --exclude=private --exclude=lost+found --exclude=images --exclude=dump --exclude=worklaptop_backup /mnt/external nas1:/mnt/datastore/backupExternal/{current_time}/"
[[external.rsync_commands]]
name = "external_only_worklaptop"
command = "-av -e ssh /mnt/external/worklaptop_backup nas1:/mnt/datastore/backupExternal/{current_time}/external"



[[targets]]
name = "gokr_perm"
instance = "brun0:gokr_perm"
mac = "d8:3a:dd:3b:84:64"
external_path = "/mnt/external/gokrazy_backup"
[[targets.rsync_commands]]
name = "Backup_waiw_from_gokrazy"
command = "-av --delete --chmod=ugo=rwx -e ssh rsync://waiw-backup/waiw /mnt/external/gokrazy_backup/waiw_backup"
[[targets.rsync_commands]]
name = "Backup_gmah_from_gokrazy"
command = "-av --delete --chmod=ugo=rwx -e ssh rsync://gmah-backup/gmah /mnt/external/gokrazy_backup/gmah_backup"


[[targets]]
name = "pinute_backup"
instance = "brun0:pinute_backup"
external_path = "/mnt/external/pinute_backup"
[[targets.rsync_commands]]
name = "Backup_pinute"
command = "-av --delete /home/brun0/nut /home/brun0/src /home/brun0/.ssh /home/brun0/.bash_profile /home/brun0/.bashrc /mnt/external/pinute_backup"


[[targets]]
name = "work_laptop"
ip = "192.168.30.5"
keypath = "/root/.ssh/id_ed25519_worklaptop"
instance = "brun0:worklaptop"
mac = "84:14:4d:f7:2a:c4"
external_path = "/mnt/external/worklaptop_backup"
[[targets.rsync_commands]]
name = "Backup_work_laptop"
command = "-av --copy-links -e ssh --exclude=personal --exclude=tools worklaptop:/home/brun0/Desktop worklaptop:/home/brun0/.ssh /mnt/external/worklaptop_backup"
